ReportOverviewApp/Models/BusinessContact.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;

namespace ReportOverviewApp.Models
{
    public class BusinessContact
    {
        public int Id { get; set; }
        [StringLength(64)]
        public string Name { get; set; }
        [StringLength(64)]
        public string BusinessOwner { get; set; }
        
        public ICollection<Report> Reports { get; set; }

        public override string ToString()
        {
            return Name;
        }
    }
}

ReportOverviewApp/Models/Deadline.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;

namespace ReportOverviewApp.Models
{
    public class ReportDeadline
    {
        public int ID { get; set; }

        [DataType(DataType.Date), DisplayFormat(DataFormatString = "{0:g}", ApplyFormatInEditMode = true)]
        public DateTime Deadline { get; set; }

        public bool IsFinished { get; set; }

        [DataType(DataType.Date), DisplayFormat(DataFormatString = "{0:g}", ApplyFormatInEditMode = true)]
        public DateTime? FinishedDate { get; set; }

        public bool IsClientNotified { get; set; }

        [DataType(DataType.Date), DisplayFormat(DataFormatString = "{0:g}", ApplyFormatInEditMode = true)]
        public DateTime? ClientNotifiedDate { get; set; }

        public bool IsSent { get; set; }

        [DataType(DataType.Date), DisplayFormat(DataFormatString = "{0:g}", ApplyFormatInEditMode = true)]
        public DateTime? SentDate { get; set; }

        [ForeignKey("ReportID")]
        public int ReportID { get; set; }
    }
}

ReportOverviewApp/Models/Plan.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace ReportOverviewApp.Models
{
    public class Plan
    {
        public int Id { get; set; }
        [StringLength(255)]
        public string Name { get; set; }
        [StringLength(64)]
        public string WindwardId { get; set; }
        public State State { get; set; }
        public int StateId { get; set; }

        public virtual ICollection<ReportPlanMap> ReportPlanMapping { get; set; }
        public bool HasTermedReports { get => ReportPlanMapping != null && ReportPlanMapping.Select(rpm => rpm.Report).Any(r => r.IsTermedOn(null)); }
        public bool HasActiveReports { get => ReportPlanMapping != null && ReportPlanMapping.Select(rpm => rpm.Report).Any(r => !r.IsTermedOn(null)); }
    }
}

ReportOverviewApp/Controllers/BusinessContactsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using ReportOverviewApp.Data;
using ReportOverviewApp.Models;
using ReportOverviewApp.Models.BusinessContactViewModels;

namespace ReportOverviewApp.Controllers
{
    [Authorize]
    public class BusinessContactsController : Controller
    {
        private readonly ApplicationDbContext _context;
        private const string unassigned = "Unassigned";
        private const int unassignedId = 0;
        public BusinessContactsController(ApplicationDbContext context)
        {
            _context = context;
        }

        public async Task<IActionResult> TransferReports(int? first, int? second)
        {
            //var firstTransfer = await _context.BusinessContacts.Include(bc => bc.Reports).SingleOrDefaultAsync(bc => bc.Id == recipientId);
            //if (owner == null || recipient == null) return NotFound();
            TransferReportsViewModel viewModel = viewModel = new TransferReportsViewModel()
            {
                BusinessContacts = await _context.BusinessContacts.Include(bc => bc.Reports).ToListAsync(),
                FirstReports = new List<int>(),
                SecondReports = new List<int>()
            };
            if (first != null && first.HasValue)
            {
                viewModel.First = first.Value;
            }
            if (second != null && second.HasValue)
            {
                viewModel.Second = second.Value;
            }
            viewModel.BusinessContacts.Add(new BusinessContact() { Name = unassigned, Id = unassignedId, Reports = await _context.Reports.Where(r => r.BusinessContactId == null || !r.BusinessContactId.HasValue).ToListAsync()});
            return View(viewModel);
        }
        [HttpPost, ValidateAntiForgeryToken]
        public async Task<IActionResult> TransferReports([FromBody] TransferReportsViewModel viewModel)
        {
            if (viewModel == null) return NotFound();
            if (ModelState.IsValid)
            {
                var firstReportsToTransfer = await _context.Reports.Where(r => r.BusinessContactId != viewModel.First && viewModel.FirstReports.Contains(r.Id)).ToListAsync();
                var secondReportsToTransfer = await _context.Reports.Where(r => r.BusinessContactId != viewModel.Second && viewModel.SecondReports.Contains(r.Id)).ToListAsync();
                if((firstReportsToTransfer == null || !firstReportsToTransfer.Any()) && (secondReportsToTransfer == null || !secondReportsToTransfer.Any()))
                {
                    return Json(new { success = true, update = false, message = "No changes detected." });
                }
                for (int i = 0; i < firstReportsToTransfer.Count(); i++)
                {
                    firstReportsToTransfer[i].BusinessContactId = (viewModel.First == unassignedId ? null : viewModel.First as int?);
                }
                for (int i = 0; i < secondReportsToTransfer.Count(); i++)
                {
                    secondReportsToTransfer[i].BusinessContactId = (viewModel.Second == unassignedId ? null : viewModel.Second as int?);
                }
                _context.UpdateRange(firstReportsToTransfer);
                _context.UpdateRange(secondReportsToTransfer);
                await _context.SaveChangesAsync();
            }
            else
            {
                return BadRequest(ModelState);
            }
            //var owner = await _context.BusinessContacts.Include(bc => bc.Reports).SingleOrDefaultAsync(bc => bc.Id == ownerId);
            //var recipient = await _context.BusinessContacts.Include(bc => bc.Reports).SingleOrDefaultAsync(bc => bc.Id == recipientId);
            //if (owner == null || recipient == null) return NotFound();
            return Json(new { success = true, update = true, message = "Save was successful"});
        }


        // GET: BusinessContacts
        public async Task<IActionResult> Index(string id, string name, string businessOwner, string sort, int? page = 1, int? take = 20)
        {
            var businessContacts = await _context.BusinessContacts.ToListAsync();
            switch (sort?.ToLower())
            {
                case "id":
                    businessContacts = businessContacts.OrderBy(p => p.Id).ToList();
                    break;
                case "name":
                    businessContacts = businessContacts.OrderBy(p => p.Name).ToList();
                    break;
                default:
                    businessContacts = businessContacts.OrderBy(p => p.Id).ToList();
                    break;

            }
            ViewData["id"] = id;
            ViewData["name"] = name;
            ViewData["sort"] = sort;
            ViewData["businessOwner"] = businessOwner;
            ViewData["page"] = page;
            ViewData["take"] = take;
           

            return View(businessContacts);
        }

        // GET: BusinessContacts/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var businessContact = await _context.BusinessContacts.Include(bc => bc.Reports)
                .SingleOrDefaultAsync(m => m.Id == id);
            if (businessContact == null)
            {
                return NotFound();
            }

            return View(businessContact);
        }

        // GET: BusinessContacts/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: BusinessContacts/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Name,Email,BusinessOwner")] BusinessContact businessContact)
        {
            if (ModelState.IsValid)
            {
                _context.Add(businessContact);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(businessContact);
        }

        // GET: BusinessContacts/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var businessContact = await _context.BusinessContacts.SingleOrDefaultAsync(m => m.Id == id);
            if (businessContact == null)
            {
                return NotFound();
            }
            return View(businessContact);
        }

        // POST: BusinessContacts/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Name,Email,BusinessOwner")] BusinessContact businessContact)
        {
            if (id != businessContact.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(businessContact);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!BusinessContactExists(businessContact.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(businessContact);
        }

        // GET: BusinessContacts/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var businessContact = await _context.BusinessContacts
                .SingleOrDefaultAsync(m => m.Id == id);
            if (businessContact == null)
            {
                return NotFound();
            }

            return View(businessContact);
        }

        // POST: BusinessContacts/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var businessContact = await _context.BusinessContacts.SingleOrDefaultAsync(m => m.Id == id);
            _context.BusinessContacts.Remove(businessContact);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool BusinessContactExists(int id)
        {
            return _context.BusinessContacts.Any(e => e.Id == id);
        }
    }
}

ReportOverviewApp/Controllers/DocsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

namespace ReportOverviewApp.Controllers
{
    
    public class DocsController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
        public IActionResult Reports()
        {
            return View();
        }
        public IActionResult Plans()
        {
            return View();
        }
        public IActionResult Deadlines()
        {
            return View();
        }
        public IActionResult BusinessContacts()
        {
            return View();
        }
    }
}

ReportOverviewApp/Controllers/PlansController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text.RegularExpressions;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using ReportOverviewApp.Data;
using ReportOverviewApp.Models;

namespace ReportOverviewApp.Controllers
{
    [Authorize]
    public class PlansController : Controller
    {
        private readonly ApplicationDbContext _context;

        public PlansController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Plans
        public async Task<IActionResult> Index(string id, string name, string state, string windwardId, string sort, int? page = 1, int? take = 20)
        {
            ViewData["id"] = id;
            ViewData["name"] = name;
            ViewData["sort"] = sort;
            ViewData["windwardId"] = windwardId;
            ViewData["state"] = state;
            ViewData["page"] = page;
            ViewData["take"] = take;
            ViewData["StateId"] = new SelectList(await _context.States.OrderBy(s => s.Name).ToListAsync(), "Id", "Name");

            return View();
        }

        //GET: Plans/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var plan = await _context.Plans
                .Include(p => p.State)
                .Include(p => p.ReportPlanMapping)
                    .ThenInclude(rpm => rpm.Report)
                        .ThenInclude(r => r.Deadlines)
                .SingleOrDefaultAsync(m => m.Id == id);
            if (plan == null)
            {
                return NotFound();
            }

            return View(plan);
        }

        // GET: Plans/Create
        public IActionResult Create()
        {
            ViewData["StateId"] = new SelectList(_context.States, "Id", "Name");
            return View();
        }

        // POST: Plans/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([FromBody] Plan plan)
        {
            if (ModelState.IsValid)
            {
                _context.Add(plan);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["StateId"] = new SelectList(_context.States, "Id", "Name", plan.StateId);
            return View(plan);
        }

        // GET: Plans/Edit/5
        [HttpGet]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var plan = await _context.Plans.SingleOrDefaultAsync(m => m.Id == id);
            if (plan == null)
            {
                return NotFound();
            }
            ViewData["StateId"] = new SelectList(_context.States, "Id", "Name", plan.StateId);
            return View(plan);
        }

        // POST: Plans/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [FromBody] Plan plan)
        {
            if (id != plan.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(plan);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!PlanExists(plan.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return Ok();
            }
            //ViewData["StateId"] = new SelectList(_context.States, "Id", "Name", plan.StateId);
            return BadRequest();
        }


        // GET: Plans/Delete/5
        [HttpGet]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var plan = await _context.Plans
                .Include(p => p.State)
                .SingleOrDefaultAsync(m => m.Id == id);
            if (plan == null)
            {
                return NotFound();
            }

            return View(plan);
        }

        // POST: Plans/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var plan = await _context.Plans.SingleOrDefaultAsync(m => m.Id == id);
            if (plan == null) return NotFound();
            _context.Plans.Remove(plan);
            await _context.SaveChangesAsync();
            return Json(new { success = true, update = true, message = "Deletion successful" });
        }

        private bool PlanExists(int id)
        {
            return _context.Plans.Any(e => e.Id == id);
        }
    }
}

ReportOverviewApp/Views/Docs/BusinessContacts.cshtml
@{
    ViewData["Title"] = "Docs (Business Contacts)";
}
<div class="row full-width">

    <div class="col-md-3">
            @await Html.PartialAsync("Categories")
    </div>
    <div class="col-md-6">
        <h3>Business Contacts</h3>
        <hr />
        <div>
            @await Html.PartialAsync("BusinessContactsDocumentation")
        </div>
    </div>
</div>

ReportOverviewApp/Views/Docs/BusinessContactsDocumentation.cshtml
<h4>
    Navigation
</h4>
<div class="container">

    <h5>Locations</h5>
    <div>
        <p><i>Url</i></p>
        <ul style="list-style:none;">
            <li><a asp-controller="BusinessContacts" asp-action="Index">Business Contacts</a></li>
            <li><a asp-controller="BusinessContacts" asp-action="TransferReports">Transfer Reports</a></li>
        </ul>
        <p><i>Navbar Location</i></p>
        <ul style="list-style:none;">
            <li><p>Located on the top of the page, the navbar has a dropdown for <strong>Business Contacts</strong>.&nbsp;&nbsp;By clicking on it, the dropdown will be exposed for the user to choose the corresponding options.</p></li>
        </ul>
    </div>
    <h5>Business Contacts</h5>
    <div>
        <p><i>Structure</i></p>
        <ul>
            <li>Title, Create New</li>
            <li>
                Pagination
                <ul>
                    <li>
                        Description:  Allows the user to decrement/increment page indices of the business contacts as well as choosing the number of business contacts to show.
                    </li>
                    <li>
                        Options
                        <ul class="list-unstyled">
                            <li>
                                <i class="fas fa-chevron-left"></i> - Decrement index (Show the previous set of records)
                            </li>
                            <li>
                                <i class="fas fa-chevron-right"></i> - Increment index (Show the next set of records)
                            </li>
                            <li>
                                <i class="fas fa-caret-down"></i> - Dropdown (Choose number of records to be displayed)
                            </li>
                        </ul>
                    </li>
                </ul>
            </li>
            <li>
                Table
                <ul>
                    <li>
                        Id
                        <ul>
                            <li>
                                Description:&nbsp;&nbsp;ID of a business contact
                            </li>
                        </ul>
                    </li>
                    <li>
                        Name
                        <ul>
                            <li>
                                Description:&nbsp;&nbsp;Name of a business contact
                            </li>
                        </ul>
                    </li>
                    <li>
                        BusinessOwner
                        <ul>
                            <li>
                                Description:&nbsp;&nbsp;Department of a business contact
                            </li>
                        </ul>
                    </li>
                    <li>
                        Options
                        <ul>
                            <li>
                                Description:&nbsp;&nbsp;Options for the user to click on for the following actions.
                            </li>
                            <li>
                                Table Header
                                <ul class="list-unstyled">
                                    <li>
                                        <i class="fas fa-search"></i> - Search
                                    </li>
                                    <li>
                                        <i class="fas fa-times"></i> - Clear search
                                    </li>
                                </ul>
                            </li>
                            <li>
                                Table Body (business contact rows)
                                <ul class="list-unstyled">
                                    <li>
                                        <i class="fas fa-edit"></i> - Managing (Edit/Delete) a business contact
                                    </li>
                                    <li>
                                        <i class="fas fa-book"></i> - View more details of a business contact
                                    </li>
                                    <li>
                                        <i class="fas fa-exchange-alt"></i> - Transfer/Add/Remove reports of a business contact
                                    </li>
                                    <li>
                                        <i class="fas fa-arrow-right"></i> - View the reports of a business contact
                                    </li>
                                </ul>
                            </li>
                        </ul>
                    </li>
                </ul>
            </li>
        </ul>
    </div>
</div>
<h4>
    Operations
</h4>
<div class="container">
    <h5>Searching business contacts</h5>
    <div>
        <p><i>When searching for a business contact</i><p />
        <p>
            <ul>
                <li>Enter text into the input fields</li>
                <li>
                    Click <i class="fas fa-search"></i> or press <kbd>Enter</kbd> to search for business contacts that meet the criteria of the input fields.
                </li>
                <li>
                    Click <i class="fas fa-times"></i> to clear all fields for searching.
                </li>
            </ul>
        </p>
    </div>
    <hr />
    <h5>Creating business contacts</h5>
    <div>
        <p><i>When creating a business contact</i><p />
        <p>
            <ul>
                <li>
                    Click <strong><i class="fas fa-plus-square"></i> Create New</strong> to open the New business contact dialog.
                </li>
                <li>
                    Enter in fields for the form.
                </li>
                <li>
                    Clicking on <strong><i class="fas fa-save"></i> Save</strong> will send a request to the server to create the business contact and save it to the database.
                </li>
                <li style="list-style:none;">
                    A success alert will be shown confirming the save request was sucessful made and processed.
                    <div class="alert alert-success"><strong>Example business contact</strong> has been successfully created.</div>
                </li>
                <li style="list-style:none;">
                    A danger alert will be shown if the save request could not be handled.
                    <div class="alert alert-danger">Something went wrong:  <strong>Error Message</strong></div>
                </li>

                <li>
                    Clicking on <strong><i class="fas fa-eraser"></i> Clear</strong> will clear all the fields in the form.
                </li>
            </ul>
        </p>
    </div>
    <hr />
    <h5>Updating business contacts</h5>
    <div>
        <p><i>When updating a business contact</i><p />
        <p>
            <ul>
                <li>
                    From the business contacts table, click on the <i class="fas fa-edit"></i> icon on a row in the <strong>Options</strong> column to open the Manage business contact dialog.
                </li>
                <li>
                    Enter in fields for the form to be changed.
                </li>
                <li>
                    Clicking on <strong><i class="fas fa-save"></i> Save</strong> will send a request to the server to create the business contact and save it to the database.
                </li>
                <li style="list-style:none;">
                    A success alert will be shown confirming the save request was sucessfully completed.
                    <div class="alert alert-success"><strong>Example business contact</strong> has been successfully updated.</div>
                </li>
                <li style="list-style:none;">
                    A danger alert will be shown if the save request could not be handled.
                    <div class="alert alert-danger">Something went wrong:  <strong>Error Message</strong></div>
                </li>

            </ul>
        </p>
    </div>
    <hr />
    <h5>Deleting business contacts</h5>
    <div>
        <p><i>When deleting a business contact</i><p />
        <p>
            <ul>
                <li>
                    From the business contacts table, click on the <i class="fas fa-edit"></i> icon on a row in the <strong>Options</strong> column to open the Manage business contact dialog.
                </li>
                <li>
                    Clicking on <strong><i class="fas fa-times"></i> Delete</strong> will ask for a confirmation before deleting.
                    <ul>
                        <li>Clicking <strong>No</strong> will cancel the confirmation.</li>
                        <li>Clicking <strong>Yes</strong> will submit a delete request for the business contact.</li>
                        <li style="list-style:none;">
                            A success alert will be shown confirming the delete request was sucessfully completed.
                            <div class="alert alert-success"><strong>Example business contact</strong> has been successfully deleted.</div>
                        </li>
                        <li style="list-style:none;">
                            A danger alert will be shown if the delete request could not be handled.
                            <div class="alert alert-danger">Something went wrong:  <strong>Error Message</strong></div>
                        </li>
                    </ul>
                </li>
            </ul>
        </p>
    </div>
</div>

ReportOverviewApp/Views/Docs/Categories.cshtml
<ul style="list-style:none; font-size: 1.2rem; position:fixed;">
    <li>Categories</li>
    <li><a asp-controller="Docs" asp-action="Reports">Reports</a></li>
    <li><a asp-controller="Docs" asp-action="Deadlines">Deadlines</a></li>
    <li><a asp-controller="Docs" asp-action="Plans">Plans</a></li>
    <li><a asp-controller="Docs" asp-action="BusinessContacts">Business Contacts</a></li>
</ul>

ReportOverviewApp/Views/Docs/Deadlines.cshtml
@{
    ViewData["Title"] = "Docs (Reports)";
}
<div class="row full-width">

    <div class="col-md-3">
        @await Html.PartialAsync("Categories")
    </div>
    <div class="col-md-6">
        <h3>Deadlines</h3>
        <hr />
        <div>
            @await Html.PartialAsync("DeadlinesDocumentation")
        </div>
    </div>
</div>

ReportOverviewApp/Views/Docs/Index.cshtml
@{
    ViewData["Title"] = "Docs";
}
<div class="row full-width">
    <div class="col-md-3">
        @await Html.PartialAsync("Categories")
    </div>
    <div class="col-md-6">
        <h3>Documentation</h3>
        <hr />
        <p>
            This page is to provide end-users information on how to navigate and utilize the web application.&nbsp;&nbsp;Clicking on the categories on the left side will show their documentation.
        </p>
    </div>
</div>

ReportOverviewApp/Views/Docs/Plans.cshtml
@{
    ViewData["Title"] = "Docs (Plans)";
}
<div class="row full-width">

    <div class="col-md-3">
        @await Html.PartialAsync("Categories")
    </div>
    <div class="col-md-6">
        <h3>Reports</h3>
        <hr />
        <div>
            @await Html.PartialAsync("PlansDocumentation")
        </div>
    </div>
</div>

ReportOverviewApp/Views/Docs/Reports.cshtml
@{
    ViewData["Title"] = "Docs (Reports)";
}
<div class="row full-width">

    <div class="col-md-3">
        @await Html.PartialAsync("Categories")
    </div>
    <div class="col-md-6">
        <h3>Reports</h3>
        <hr />
        <div>
            @await Html.PartialAsync("ReportsDocumentation")
        </div>
    </div>
</div>